### ISSUE TITLE
 user@HP-Z8-G4-Workstation:~/cuFHE-master/cufhe/python$ python test_circuits_gpu.py Traceback (most recent call last):   File "test_circuits_gpu.py", line 23, in <module>     import lib.fhe_gpu as fhe   File "/home/user/cuFHE-master/cufhe/python/lib/fhe_gpu.py", line 59     fhe.Encrypt(ctxt.ctxt_, ptxt, prikey)  ^ TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by bpradeep508** [vernamlab/cuFHE#16]

**Comment by muyixi315** [comment]
The code formatting issue arises from inconsistent indentation styles, specifically the mixed use of tabs and spaces. To resolve this, it's essential to unify the indentation style across the entire codebase. It is recommended to use 4 spaces for indentation, as per standard conventions.
